baseURL = "http://stoneporchconsulting.com/"
languageCode = "en-us"
title = "Stone Porch Consulting"


theme = "strata"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Philip Nelson"
	description = "Stone Porch Consulting"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/overrides.css"]

  [params.avatar]
    hide = true
	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = ""
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Philip Nelson**<br>computer systems architecture<br>software development<br>devops<br>security"
		# The icons will be shown if you enter your username
		twitter = "panmanphil"
		github = "panmanphil"
		gitlab = ""
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "philipanelson"

		copyright = [
			"&copy; Philip Nelson",
			"Design: [HTML5 UP](//html5up.net)"
		]


	[params.about]
		hide  = false
		title = "Stone Porch Consulting"
		content = "Stone Porch Consulting is the name of the independent business from which I do my work as a consultant and contractor. I have had the luxury of working primarily via word of mouth connections so am able to keep the web presence pretty simple!"


	[params.portfolio]
		hide  = false
		title = "What I do"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "system-architecture.png"
			thumb = "headshot.jpg"
			title = "Systems architecture"
			description = "It starts with a system design."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "DevOps"
			description = "Build Automation, CI/CD, Infrastructure setup in AWS and Azure"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Security."
			description = "Identity, authentication, authorization, profile management, MFA, reviews, audit preparation."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Software development."
			description = "Yes, I write code, work as a contractor, consultant, or whatever combination you need."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "IOT."
			description = "Cloud based interfaces to hardware devices, with access to an electrical engineer."


	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = ""
		content = ""

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = ""
		address = [
			"Green Bay, WI 54301",
			"United States"
		]
		phone = "920-437-3413"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = ""

		

# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "http://panmanphil.wordpress.com"
	weight = 0

